# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lavimoe\Desktop\cs2019\sample.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 812)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(50, 389, 281, 341))
        self.listView.setObjectName("listView")
        self.originalImageDisplay = QtWidgets.QLabel(self.centralwidget)
        self.originalImageDisplay.setGeometry(QtCore.QRect(360, 100, 680, 630))
        self.originalImageDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.originalImageDisplay.setFrameShadow(QtWidgets.QFrame.Plain)
        self.originalImageDisplay.setLineWidth(1)
        self.originalImageDisplay.setMidLineWidth(0)
        self.originalImageDisplay.setObjectName("originalImageDisplay")
        self.addPortBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addPortBtn.setEnabled(True)
        self.addPortBtn.setGeometry(QtCore.QRect(50, 94, 100, 50))
        self.addPortBtn.setObjectName("addPortBtn")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 198, 100, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(50, 146, 100, 50))
        self.pushButton.setObjectName("pushButton")
        self.importImageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.importImageBtn.setEnabled(True)
        self.importImageBtn.setGeometry(QtCore.QRect(360, 50, 81, 31))
        self.importImageBtn.setObjectName("importImageBtn")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 250, 100, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.importImageBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.importImageBtn_2.setEnabled(True)
        self.importImageBtn_2.setGeometry(QtCore.QRect(460, 50, 81, 31))
        self.importImageBtn_2.setObjectName("importImageBtn_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCell_Only = QtWidgets.QAction(MainWindow)
        self.actionCell_Only.setObjectName("actionCell_Only")
        self.actionLink_Only = QtWidgets.QAction(MainWindow)
        self.actionLink_Only.setObjectName("actionLink_Only")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSelect = QtWidgets.QAction(MainWindow)
        self.actionSelect.setObjectName("actionSelect")
        self.actionSelect_All = QtWidgets.QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuView.addAction(self.actionCell_Only)
        self.menuView.addAction(self.actionLink_Only)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.originalImageDisplay.setText(_translate("MainWindow", "TextLabel"))
        self.addPortBtn.setText(_translate("MainWindow", "Add Point"))
        self.pushButton_4.setText(_translate("MainWindow", "Add Wire"))
        self.pushButton.setText(_translate("MainWindow", "Remove Point"))
        self.importImageBtn.setText(_translate("MainWindow", "Import Image"))
        self.pushButton_5.setText(_translate("MainWindow", "Remove Wire"))
        self.importImageBtn_2.setText(_translate("MainWindow", "Remove Image"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionCell_Only.setText(_translate("MainWindow", "Cell Only"))
        self.actionLink_Only.setText(_translate("MainWindow", "Nanowire Only"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionSelect.setText(_translate("MainWindow", "Select"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
